#!/usr/bin/env bash

ldapsearch -x \
    -H ldaps://ldap.cesnet.cz \
    -b "ou=People,dc=cesnet,dc=cz" \
    -D 'uid=jop,ou=people,dc=cesnet,dc=cz' \
    -W \
    "(|(uid=*$1*)(cn=*$1*))" \
    cn\;lang-en mail preferedMail authorisedMail telephonenumber mobile ipphone \
    | grep -v \# \
    | grep -v "^$" \
    | grep -v ^search \
    | grep -v ^result \
    | grep -v ^version \
    | sed "s/^dn/#dn/" \
    | tr "#" "\n"
