#!/usr/bin/env bash

ldapsearch -x -h ldap1.cesnet.cz -b "ou=People,dc=cesnet,dc=cz" "(|(uid=*$1*)(cn=*$1*))" cn\;lang-en mail telephonenumber mobile ipphone | grep -v \# | grep -v "^$" | grep -v ^search | grep -v ^result | grep -v ^version | sed "s/^dn/#dn/" | tr "#" "\n"
